# Generated by Django 4.2.19 on 2025-03-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_four_digits', models.CharField(max_length=4)),
                ('holder', models.CharField(max_length=100)),
                ('expiry_year', models.CharField(max_length=4)),
                ('expiry_month', models.CharField(max_length=3)),
                ('branch', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
