# Generated by Django 4.2.19 on 2025-03-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_bin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card',
            table='cards',
        ),
    ]
